@startuml Self RAG

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam wrapWidth 200
skinparam maxMessageSize 200

!$BLACK = "#black"
!$COLOR_A_6 = "#d4de5e"
!$COLOR_A_5 = "#7f3b08"
!$COLOR_A_4 = "#b35806"
!$COLOR_A_3 = "#e08214"
!$COLOR_A_2 = "#fdb863"
!$COLOR_A_1 = "#fee0b6"
!$COLOR_NEUTRAL = "#f7f7f7"
!$COLOR_B_1 = "#d8daeb"
!$COLOR_B_2 = "#b2abd2"
!$COLOR_B_3 = "#8073ac"
!$COLOR_B_4 = "#542788"
!$COLOR_B_5 = "#2d004b"
!$COLOR_REL_LINE = "#8073ac"
!$COLOR_REL_TEXT = "#8073ac"

UpdateElementStyle("container", $bgColor=$COLOR_A_6, $fontColor=$BLACK, $borderColor=$COLOR_A_1, $shadowing="false", $legendText="Internal user")
UpdateElementStyle("system", $bgColor=$COLOR_B_4, $fontColor=$COLOR_NEUTRAL, $borderColor=$COLOR_B_2, $legendText="External system")
UpdateRelStyle($lineColor=$COLOR_REL_LINE, $textColor=$COLOR_REL_TEXT)

LAYOUT_WITH_LEGEND()

'System(start, "Start")
'System(END, "END")


Boundary(c1, "Transformation") {
    Container(rewrite_node, "rewrite_node")  
    Container(decompose_node, "decompose_node")        
}

Boundary(c2, "parallel_retriever") {
    SystemQueue_Ext(continue_retriever, "continue_retriever")

    Container(retrieve_node1, "retriever")
    Container(retrieve_node2, "retriever")
    Container(retrieve_node3, "retriever")
}    

Boundary(c3, "parallel_grader") {
    SystemQueue_Ext(continue_grader, "continue_grader")

    Container(grade_node1, "grader")
    Container(grade_node2, "grader")
    Container(grade_node3, "grader")  
    Container(grade_node4, "grader")  
    Container(grade_node5, "grader")  
    Container(grade_node6, "grader")  
}

Container(generate_node, "generate_node")    

Rel(Start, rewrite_node, "query")

Rel(rewrite_node, decompose_node, "revised query")

Rel(decompose_node, continue_retriever, "sub-queries")

Rel(continue_retriever, retrieve_node1, "sub-query1")
Rel(continue_retriever, retrieve_node2, "sub-query2")
Rel(continue_retriever, retrieve_node3, "sub-query3")


Rel(retrieve_node1, continue_grader, "relevant\ndocs1")
Rel(retrieve_node2, continue_grader, "relevant\ndocs2")
Rel(retrieve_node3, continue_grader, "relevant\ndocs3")

Rel(continue_grader, grade_node1, "relevant\ndoc A")
Rel(continue_grader, grade_node2, "relevant\ndoc B")
Rel(continue_grader, grade_node3, "relevant\ndoc C")
Rel(continue_grader, grade_node4, "relevant\ndoc D")
Rel(continue_grader, grade_node5, "relevant\ndoc E")
Rel(continue_grader, grade_node6, "relevant\ndoc F")

Rel(grade_node1, generate_node, "filtered\ndocs A")
Rel(grade_node2, generate_node, "filtered\ndocs B")
Rel(grade_node3, generate_node, "filtered\ndocs C")
Rel(grade_node4, generate_node, "filtered\ndocs D")
Rel(grade_node5, generate_node, "filtered\ndocs E")
Rel(grade_node6, generate_node, "filtered\ndocs F")

Rel(generate_node, END, "result")

@enduml